version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  test:
    jobs:
      - setup-dotenv:
          name: Setup dotenv
          command: |
            cp .env.example .env
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: "20.0"
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm
