version: 2.1

orbs:
  node: circleci/node@5.2

commands:
  init-node:
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Copy .env.example to .env
          command: cp .env.example .env

jobs:
  build-node:
    executor: node/default
    steps:
      - init-node
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - init-node
      - run:
          name: Run tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/
  deploy-dev:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to dev
          command: echo "Deploying to dev"
  deploy-prod:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to prod
          command: echo "Deploying to prod"

workflows:
  build-and-test:
    jobs:
      - build-node
      - test-node
      - deploy-dev:
          requires:
            - test-node
            - build-node
          filters:
            branches:
              only:
                - dev
      - deploy-prod:
          requires:
            - test-node
            - build-node
          filters:
            branches:
              only:
                - main
