version: 2.1

orbs:
  node: circleci/node@5.2

workflows:
  test:
    jobs:
      - run:
          name: Setup dotenv
          command: |
            cp .env.example .env
      - node/test:
          version: "20.0"
          pkg-manager: npm
